### ISSUE TITLE
BUG INSCRIPTIONS

### ISSUE THREAD

**Issue by darkelfist** [ceedledev/FreeGen#1]
YO j'ai utiliser le code source je me suis co a ma db mais quand j ai voulue m'inscrire sur mon site avec le code sa n'a pas marcher regarder par vous meme sur ultra-gen.rf.gd si vous savez pourquoi sa ne marche pas contecter moi sur discord alerte noix de coco#0667

**Comment by darkelfist** [comment]
alerte noix de coco#0667

**Comment by 0xIntel** [comment]
accepte moi : ketAma#8262

**Comment by darkelfist** [comment]
> accepte moi : ketAma#8262

renvoie une demande sur se compte alerte noix de coco#7603
