### ISSUE TITLE
Tarping gênant ton vieux leak 

### ISSUE THREAD

**Issue by julesz2332** [ceedledev/FreeGen#3]
Ton leak mal codé avec plein de failles, avec le bug inscription, loading infini, et les fonctionnalité de base que tu peut trouver sur le site à Lukas aucune utilité tu veux juste faires des "stars" t'es trop gênant mais sache qu'on te bz ta d la pute fdp mdrr :)))

**Comment by ceedledev** [comment]
le code date de 2 ans poto, puis kestu me fait le bandi sur le web ta grand mère la pute irl tu bouge pas pd
