### ISSUE TITLE
Jremet vu que tu suppr petite salp

### ISSUE THREAD

**Issue by julesz2332** [ceedledev/FreeGen#4]
**### le code date de 2 ans poto, puis kestu me fait le bandi sur le web ta grand mère la pute irl tu bouge pas pd**

Je fais aucunement le bandits contrairement à toi poto mdrr va leak tes vieux codes source ailleurs, tu voulais juste te faire une réput assume mais t'es qu'une pute hein l'oublie pas mdrr

**Comment by ceedledev** [comment]
c bien cque je pensé ta mere c vrm une grosse saloppe qui t’a loupé a la naissance toi, la source date de 2 ans faut je lecrie en gras ou tu comprend la ? puis tu me parle de « leak » alors que c’est juste une réadaptation du code pour ajouter un espace VIP qui a cette appoque vue que t encore un petit n’avait pas ce système. donc bon c bien beau de dire « slp » alors que sa assume pas des rencontre irl 😆 c bien beau internet mais on est en 2024 poto les generateur c encore 10x + gênant que de proposer a l’epoque une source « leak » avec un système de VIP intégrer MDRRRR
