### ISSUE TITLE
julesz2332 t gênant a creer des issues pour manger le seum MDRRRR

### ISSUE THREAD

**Issue by julesz2332** [ceedledev/FreeGen#5]
### c bien cque je pensé ta mere c vrm une grosse saloppe qui t’a loupé a la naissance toi, la source date de 2 ans faut je lecrie en gras ou tu comprend la ? puis tu me parle de « leak » alors que c’est juste une réadaptation du code pour ajouter un espace VIP qui a cette appoque vue que t encore un petit n’avait pas ce système. donc bon c bien beau de dire « slp » alors que sa assume pas des rencontre irl 😆 c bien beau internet mais on est en 2024 poto les generateur c encore 10x + gênant que de proposer a l’epoque une source « leak » avec un système de VIP intégrer MDRRRR****

déjà en partant de principe que sans leak de base tu n'aurais jamais sortis cette source vu que ton niveau en développement, dois être déplorable, de plus tu as quelle âge ? t'a pas honte de skid full projet, de plus cherche pas d'excuse stp avec un petit système en plus c'est que du copier coller, et part pas sur un autre sujet de rencontre irl, car je te pine t'a mère irl crois le ou non, et gênant de "MDR" 
plus jms stp

**Comment by julesz2332** [comment]
comme jdis c'est juste pr les star sale pute mdrrr assume

**Comment by ceedledev** [comment]
pas bien de manger le seum car je suis le #1 des repos github et depuis 2 ans sombre merde puis rep discord qu’on ce fasse la rencontre irl que jte bz bien puis après t’aura ta place dans ce github, puis tkt nv dev je suis un champion 😆 2 ans après tu repond comme meme sombre merde MDRRRRR
