### ISSUE TITLE
RP

### ISSUE THREAD

**Issue by julesz2332** [ceedledev/FreeGen#6]
**pas bien de manger le seum car je suis le https://github.com/ceedledev/FreeGen/issues/1 des repos github et depuis 2 ans sombre merde puis rep discord qu’on ce fasse la rencontre irl que jte bz bien puis après t’aura ta place dans ce github, puis tkt nv dev je suis un champion 😆 2 ans après tu repond comme meme sombre merde MDRRRRR**

Mdrrr jviens juste de voir ce repos (gênant) donc non j'ai aucun seum mdrrr, de plus et moi j'suis chaud je veut bien te répondre mais commence par m'ajouter puis m'envoie un message c'est mieux non ? mdrr sale merde de plus la sombre merde c'est toi mdrr à encore fais des leaks générateurs pour promouvoir ton vieux serveurs de joinsmember tu fais tiep plus jamais sa aussi mdrr slp que t'es

**Comment by ceedledev** [comment]
avec toi j’ai remarqué je me répète et j’ai bien raison ta grosse mere la pute elle ta bien bifler le crâne quand tétais petit sombre pute comme ta mere j’ai juré SA DATE DE 2 ANS poto t’arrive pas a te le rentrer dans le crâne MDRRRR puis sa parle de gênant et que je « vole le projet » mais bon sa créé un repos pour rien pour juste pub freegen.nl qui n’est meme pas le vrai freegen MDRRRR moi je dit honteux 🤣 puis moneycatoff sur discord ajt mtn vue que ta dla bouche ecrit sombre merde 
![IMG_0431](https://github.com/user-attachments/assets/55a5bda8-fa15-4ce0-9608-d1ebb982b8ae)
