### ISSUE TITLE
Payo

### ISSUE THREAD

**Issue by julesz2332** [ceedledev/FreeGen#7]
**avec toi j’ai remarqué je me répète et j’ai bien raison ta grosse mere la pute elle ta bien bifler le crâne quand tétais petit sombre pute comme ta mere j’ai juré SA DATE DE 2 ANS poto t’arrive pas a te le rentrer dans le crâne MDRRRR puis sa parle de gênant et que je « vole le projet » mais bon sa créé un repos pour rien pour juste pub freegen.nl qui n’est meme pas le vrai freegen MDRRRR moi je dit honteux 🤣 puis moneycatoff sur discord ajt mtn vue que ta dla bouche ecrit sombre merde**

Frrot tu t'es tromper sur toute la lignes je te l'ai dis je viens de voir ce repos qui est gênant mdrr et y'a aucun rapport entre le repos et les 2ans tu whippin trop de chose, et oue jcrée un repos fgen et alr ? y'a pas de leak frérot mdrr de plus envoie nous les preuves que ce n'est pas le vrai t'es un bizzard toi ?! mdrr de plus ajoute le bon comptes stp et de plus j'mapel pas julesz ct bz sa réput car lui aussi c'est une pute comme t'en ai une, d'ailleurs je m'autoriserais à faire la même choses tkt pas pour sa, tiens ajt sale chiens que t'es grosse merde flecheurs incompétant devlopeur nique tes mort: uhqksz
![image](https://github.com/user-attachments/assets/e966db36-9ee6-4c7a-82a8-791bc079b980)

**Comment by julesz2332** [comment]
![image](https://github.com/user-attachments/assets/5bbfe4f4-6402-4cee-952e-033ac0fa6644)
sa parle de réponse mais sa répond plus j'imagine pas un rdv irl... alors parle pas trop salope que t'es

**Comment by ceedledev** [comment]
pas bien d’inventer des mensonges, je lui propose de voc sa l’intéresse pas donc bon en attente de vous relire chères KSZ

**Comment by julesz2332** [comment]
sa fais 40 minutes que j'lavais envoyé encore heureux qui l'es rép faut savoir que c qqd mm une salope hein*

**Comment by ceedledev** [comment]
ce mots sort tous le temps de ta bouche qu’on dirait que sa ta tromatisé d’être une saloppe que tu ldis a tous le monde mais breff parlons sur Discord puis en appel c largement mieux 😉

**Comment by julesz2332** [comment]
Mais c'est norml t'es qu'une salope mdrr tu veux jdises quoi d'autre mdrr salope ?

**Comment by 002-sans** [comment]
BAHAHAH JVIENS DE TOMBER SUR CETTE ISSUE, Y A UN GARS APRES 2 ANS IL EST VENU TE FAIRE CHIER DMMDMDRRRR
sah ils ont du temps à perdre

**Comment by ceedledev** [comment]
@xvqm sans commentaire 🤣
